Add remote banlist functionalities
R2Northstar/NorthstarMasterServer pull request #37
Opened 2022-02-23 17:53 UTC by wolf109909

combined with https://github.com/R2Northstar/NorthstarLauncher/pull/94
:3
pwease work uwu

2022-02-23 18:04 UTC, barnabwhy requested changes

2022-02-23 18:04 UTC, barnabwhy commented on server/banlist.js
> +		return fileBuffer
Might also just be better to store the banlist and update the variable on file change to reduce the fs overhead, depends on how big the file is though cause memory is precious

2022-02-23 18:04 UTC, barnabwhy commented on server/banlist.js
> +    fastify.get( '/server/update_banlist', async ( request, response ) => {
Might be worth changing to
```suggestion
    fastify.get( '/server/banlist_hash', async ( request, response ) => {
```
for easy of understanding

2022-10-22 04:14 UTC, pg9182 commented
We are not currently planning to merge this.

2022-10-22 04:14 UTC, closed without merging