Add ghost server logic
R2Northstar/NorthstarMasterServer pull request #41
Opened 2022-02-28 17:48 UTC by barnabwhy

Allows servers to reregister with the same id without any change to launcher code

2022-02-28 17:49 UTC, barnabwhy commented
Finally, functioning pr :trollface:

2022-03-03 23:05 UTC, abarichello requested changes

2022-03-03 23:05 UTC, abarichello commented on server/gameserver.js
> +	let newServer = new GameServer( name, description, playerCount, request.query.maxPlayers, request.query.map, request.query.playlist, request.ip, ghost.port, ghost.authPort, request.query.password, m
You should refactor this section into a common function since this is basically a copypaste from `SharedTryAddServer`

2022-03-04 00:26 UTC, barnabwhy commented
![image](https://user-images.githubusercontent.com/22575741/156675765-b2b58ec0-0d8a-49b7-b43f-2f305d800ca6.png)
fuck

2022-03-04 22:45 UTC, abarichello approved these changes
Thanks

2022-03-04 22:45 UTC, merged