Add client/mainmenupromos.json to .gitignore
R2Northstar/NorthstarMasterServer pull request #65
Opened 2022-05-04 16:10 UTC by barnabwhy

2022-05-05 11:11 UTC, GeckoEidechse requested changes
`client/mainmenupromodata..template.json`
should probably be
`client/mainmenupromodata.template.json`
(one dot instead of two)

2022-05-08 16:13 UTC, GeckoEidechse approved these changes

2022-05-31 22:24 UTC, GeckoEidechse commented
Self-reminder to merge https://github.com/R2Northstar/NorthstarWiki/pull/82 once this one gets merged.

2022-10-22 04:11 UTC, pg9182 commented
Superseded by [R2Northstar/Atlas](https://github.com/R2Northstar/Atlas/blob/0cec719bf38ce61f9176b2cf5094c5e7e8f0529b/pkg/atlas/config.go#L124-L127).

2022-10-22 04:11 UTC, closed without merging